name: CI Workflow

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master, dev ]

jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Parent Repository
        uses: actions/checkout@v4

      - name: Checkout Next.js Repository
        uses: actions/checkout@v4
        with:
          repository: Latitude-OpenDATA-SIO-Saintbe/nextjs-repo  # Replace with your organization name and repo
          path: nextjs
          token: ${{ secrets.ORG_PAT }}  # Use the secret for PAT

      - name: Checkout Laravel Repository
        uses: actions/checkout@v4
        with:
          repository: Latitude-OpenDATA-SIO-Saintbe/laravel-repo  # Replace with your organization name and repo
          path: laravel
          token: ${{ secrets.ORG_PAT }}  # Use the secret for PAT

      - name: Checkout .NET Repository
        uses: actions/checkout@v4
        with:
          repository: Latitude-OpenDATA-SIO-Saintbe/dotnet-repo  # Replace with your organization name and repo
          path: dotnet
          token: ${{ secrets.ORG_PAT }}  # Use the secret for PAT

      - name: Setup Node.js for Next.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install Next.js Dependencies
        run: |
          cd nextjs
          npm ci

      - name: Install Playwright Browsers
        run: |
          cd nextjs
          npx playwright install --with-deps

      - name: Build and Run Docker Compose
        run: |
          cd laravel
          docker-compose up -d
          sleep 10  # Adjust this time if necessary

      - name: Run Playwright Tests
        run: |
          cd nextjs
          npx playwright test

      - name: Run Jest Tests
        run: |
          cd nextjs
          npm run test

      - name: Run Laravel Tests (if applicable)
        run: |
          cd laravel
          php artisan test  # Adjust this command according to your Laravel testing setup

      - name: Stop Docker Compose
        run: |
          cd laravel
          docker-compose down

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: nextjs/playwright-report/
          retention-days: 30
